/**
 * Execution provider abstraction.
 *
 * The production execution provider executes ONLY explicitly approved,
 * allow-listed structured operations. Arbitrary shell commands generated by
 * an LLM are never executed. Every execution produces a structured result
 * that is persisted in the executions table and audit log.
 */

export type StructuredOp =
  | { op: "rollback_deployment"; service: string; version?: string }
  | { op: "restart_service"; service: string }
  | { op: "scale_service"; service: string; replicas: number }
  | { op: "run_readonly_check"; service: string; check: string };

export interface ExecutionResult {
  status: "succeeded" | "failed";
  result: string;
  error?: string;
}

export interface ExecutionProvider {
  readonly providerType: string;
  readonly providerName: string;
  execute(op: StructuredOp): Promise<ExecutionResult>;
}

/** Allow-listed operation registry — the only ops any provider may execute. */
export const ALLOWED_OPS = [
  "rollback_deployment",
  "restart_service",
  "scale_service",
  "run_readonly_check",
] as const;

export function isAllowedOp(op: string): op is StructuredOp["op"] {
  return (ALLOWED_OPS as readonly string[]).includes(op);
}